### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by sulymankorj** [skomarica/alfresco-share-create-link#1]
Please can you inform me how I can install it

**Comment by krishandeo** [comment]
Hi, I installed both AMP file into my alfresco.war and it's showing installed successfully. Now when I am restarting my server I am not able to see link option in any documents. Please help

**Comment by mathieuga** [comment]
Please note that both AMP's have to be applied: create-link-repo.amp to alfresco.war and create-link-share.amp to share.war application. 
I guess that you have not (correctly) installed create-link-repo AMP. 

Verify if create-link-repo.amp is in /alfresco/amp
Verify if create-link-share.amp is in /alfresco/amps_share

**Comment by krishandeo** [comment]
thank you so much, Now I want to create link using java(apache-chemistry) instead of creating link from GUI. Can you please tell me how to achieve this? thank you again

**Comment by mathieuga** [comment]
Sorry i not a developer i just know how use creating link from GUI.

What is your use case ?
Skomarica make a good job with this plugin. But may be now it is better to use smart folder ?
http://docs.alfresco.com/community/concepts/sf-intro.html

**Comment by skomarica** [comment]
@krishandeo As far as I'm concerned, Apache Chemistry doesn't support creating links, as links are not part of the CMIS specification.

"Create link" is a custom Alfresco action built as a repo/share extension, like many others that are not part of the CMIS spec.
